#!/bin/sh
# =============================================================================
#  Pokedex.pak — Multi-Game Pokédex for NextUI / MinUI (tg5040)
#
#  Data format
#  -----------
#  Each game lives in data/games/<slug>/ and contains:
#    game.conf      — key=value metadata (generated by csv_to_pak.py)
#    pokemon.tsv    — universal tab-separated data (generated by csv_to_pak.py)
#
#  TSV column order (do not change — must match csv_to_pak.py TSV_COLS):
#    1  dex_id        13  ability1
#    2  national_id   14  ability2
#    3  name          15  hidden_ability
#    4  type1         16  evo_from
#    5  type2         17  evo_method
#    6  form_tag      18  evo_into
#    7  hp            19  location
#    8  atk           20  catch_rate
#    9  def           21  gender_ratio
#   10  spa           22  egg_group1
#   11  spd           23  egg_group2
#   12  spe           24  description
#
#  To add a new game:
#    1. Fill in tools/pokemon.csv and tools/game_meta.csv (see POKEDEX_CSV_SPEC.md)
#    2. Run: python3 tools/csv_to_pak.py --game my-slug
#    3. Copy output/my-slug/ → data/games/my-slug/
# =============================================================================

PAK_DIR="$(dirname "$0")"
PAK_NAME="$(basename "$PAK_DIR")"
PAK_NAME="${PAK_NAME%.*}"

rm -f "$LOGS_PATH/$PAK_NAME.txt"
exec >>"$LOGS_PATH/$PAK_NAME.txt" 2>&1
echo "$0" "$*"
cd "$PAK_DIR" || exit 1

architecture=arm
if uname -m | grep -q '64'; then
    architecture=arm64
fi

export HOME="$SHARED_USERDATA_PATH/$PAK_NAME"
mkdir -p "$HOME"

CAUGHT_FILE="$HOME/caught.txt"
touch "$CAUGHT_FILE"

is_caught() { grep -q "^$1$" "$CAUGHT_FILE"; }
toggle_caught() {
    if is_caught "$1"; then
        grep -v "^$1$" "$CAUGHT_FILE" > "$CAUGHT_FILE.tmp"
        mv "$CAUGHT_FILE.tmp" "$CAUGHT_FILE"
    else
        echo "$1" >> "$CAUGHT_FILE"
    fi
}

export PATH="$PAK_DIR/bin/$PLATFORM:$PAK_DIR/bin/$architecture:$PAK_DIR/bin/shared:$PATH"

GAMES_DIR="$PAK_DIR/data/games"
GAME_LIST_JSON="$HOME/game_list.json"
POKE_LIST_JSON="$HOME/poke_list.json"
DETAIL_JSON="$HOME/detail.json"

# ---------- Persistence -------------------------------------------------------
write_setting() { echo "$2" > "$HOME/$1"; }
read_setting()  {
    [ -f "$HOME/$1" ] && cat "$HOME/$1" && return
    [ -n "$2" ] && echo "$2"
}

# ---------- Read a key from game.conf ----------------------------------------
conf_field() {
    grep "^$2=" "$1/game.conf" 2>/dev/null | cut -d= -f2-
}

# ---------- JSON string escaping ----------------------------------------------
# Escapes backslashes and double-quotes so values are safe inside JSON strings.
# Usage: escaped=$(json_escape "$raw_value")
json_escape() {
    printf '%s' "$1" \
        | sed 's/\\/\\\\/g' \
        | sed 's/"/\\"/g'
}

# ---------- Type colour -------------------------------------------------------
type_color() {
    case "$1" in
        Normal)   echo "#A8A878" ;;
        Fire)     echo "#F08030" ;;
        Water)    echo "#6890F0" ;;
        Electric) echo "#F8D030" ;;
        Grass)    echo "#78C850" ;;
        Ice)      echo "#98D8D8" ;;
        Fighting) echo "#C03028" ;;
        Poison)   echo "#A040A0" ;;
        Ground)   echo "#E0C068" ;;
        Flying)   echo "#A890F0" ;;
        Psychic)  echo "#F85888" ;;
        Bug)      echo "#A8B820" ;;
        Rock)     echo "#B8A038" ;;
        Ghost)    echo "#705898" ;;
        Dragon)   echo "#7038F8" ;;
        Dark)     echo "#705848" ;;
        Steel)    echo "#B8B8D0" ;;
        Fairy)    echo "#EE99AC" ;;
        *)        echo "#68A090" ;;
    esac
}

# ---------- Stat bar (ASCII fill, max width 20 chars, scale 0-255) -----------
stat_bar() {
    val="$1"
    [ -z "$val" ] && echo "—" && return
    filled=$(( (val * 20) / 255 ))
    [ "$filled" -gt 20 ] && filled=20
    empty=$((20 - filled))
    bar=""
    n=0
    while [ "$n" -lt "$filled" ]; do bar="${bar}█"; n=$((n+1)); done
    n=0
    while [ "$n" -lt "$empty"  ]; do bar="${bar}░"; n=$((n+1)); done
    echo "$bar"
}

# =============================================================================
#  GAME SELECT SCREEN
# =============================================================================
build_game_list_json() {
    last=$(read_setting "selected_game" "0")
    {
        printf '{\n  "selected": %s,\n  "items": [\n' "$last"
        first=1
        for gd in "$GAMES_DIR"/*/; do
            [ -f "$gd/game.conf" ] || continue
            [ -f "$gd/pokemon.tsv" ] || continue
            gname=$(json_escape "$(conf_field "$gd" "name")")
            gyear=$(conf_field "$gd" "year")
            gtype=$(conf_field "$gd" "type")
            gcount=$(conf_field "$gd" "entry_count")
            gdex=$(json_escape "$(conf_field "$gd" "dex_label")")
            gcolor=$(conf_field "$gd" "color")
            if [ "$gtype" = "fan" ]; then badge="[FAN]"; else badge="[OG] "; fi
            label=$(json_escape "${badge}  ${gname}  —  ${gdex}  |  ${gcount} entries  (${gyear})")
            [ "$first" = "1" ] && first=0 || printf ',\n'
            printf '    {"name": "%s", "features": {"background_color": "%s"}}' \
                "$label" "$gcolor"
        done
        printf '\n  ]\n}\n'
    } > "$GAME_LIST_JSON"
}

get_game_dir_by_index() {
    target="$1"; idx=0
    for gd in "$GAMES_DIR"/*/; do
        [ -f "$gd/game.conf" ] || continue
        [ -f "$gd/pokemon.tsv" ] || continue
        [ "$idx" = "$target" ] && echo "$gd" && return
        idx=$((idx + 1))
    done
}

# =============================================================================
#  POKEMON LIST  — built with a single awk pass (O(n), not O(n²))
# =============================================================================
build_poke_list_json() {
    gd="$1"
    data="$gd/pokemon.tsv"
    slug="${gd%/}"; slug="${slug##*/}"
    last=$(read_setting "poke_$slug" "0")

    # Read caught list into a space-separated string for awk
    caught_list=$(cat "$CAUGHT_FILE" | xargs echo)

    awk -v selected="$last" -v caught_str="$caught_list" -v pak_dir="$PAK_DIR" '
    BEGIN {
        FS = "\t"
        # Build caught map
        split(caught_str, caught_array, " ")
        for (i in caught_array) caught[caught_array[i]] = 1

        # Build the type→color map in awk
        color["Normal"]   = "#A8A878"; color["Fire"]     = "#F08030"
        color["Water"]    = "#6890F0"; color["Electric"] = "#F8D030"
        color["Grass"]    = "#78C850"; color["Ice"]      = "#98D8D8"
        color["Fighting"] = "#C03028"; color["Poison"]   = "#A040A0"
        color["Ground"]   = "#E0C068"; color["Flying"]   = "#A890F0"
        color["Psychic"]  = "#F85888"; color["Bug"]      = "#A8B820"
        color["Rock"]     = "#B8A038"; color["Ghost"]    = "#705898"
        color["Dragon"]   = "#7038F8"; color["Dark"]     = "#705848"
        color["Steel"]    = "#B8B8D0"; color["Fairy"]    = "#EE99AC"
        default_color     = "#68A090"

        printf "{\n  \"selected\": %s,\n  \"items\": [\n", selected
        first = 1
    }
    NR == 1 { next }
    /^[[:space:]]*$/ { next }
    {
        dex_id  = $1; name = $3; type1 = $4; type2 = $5; form = $6
        if (dex_id == "") next

        pad = sprintf("%03d", dex_id + 0)
        ts = (type2 == "") ? type1 : type1 "/" type2
        lbl = (form != "") ? "#" pad "  " name "  [" ts "]  (" form ")" : "#" pad "  " name "  [" ts "]"

        gsub(/\\/, "\\\\", lbl); gsub(/"/, "\\\"", lbl)
        col = (type1 in color) ? color[type1] : default_color

        # Icon and Badge paths
        icon_path = pak_dir "/data/sprites/" pad ".png"
        
        # Composite Badge Logic: {type1}[_{type2}][_caught].png
        b_name = type1
        if (type2 != "") b_name = b_name "_" type2
        if (dex_id in caught) b_name = b_name "_caught"
        badge_path = pak_dir "/data/badges/" b_name ".png"

        if (!first) printf ",\n"
        first = 0
        printf "    {\"name\": \"%s\", \"features\": {\"background_color\": \"%s\"", lbl, col
        printf ", \"icon\": \"%s\"", icon_path
        printf ", \"badge\": \"%s\"", badge_path
        printf "}}"
    }
    END { printf "\n  ]\n}\n" }
    ' "$data" > "$POKE_LIST_JSON"
}

# =============================================================================
#  DETAIL VIEW  — single awk pass to read all columns, then shell assembles slides
# =============================================================================
build_detail_json() {
    gd="$1"; lnum="$2"
    data="$gd/pokemon.tsv"

    # Validate lnum is in range; clamp to 1 if not
    total=$(awk 'NR>1 && !/^[[:space:]]*$/{n++} END{print n+0}' "$data")
    if [ -z "$lnum" ] || [ "$lnum" -lt 1 ] || [ "$lnum" -gt "$total" ]; then
        lnum=1
    fi

    # Read all 24 fields in a single awk call (NR==lnum+1 because of header)
    # Output: one field per line, in column order.
    eval "$(awk -v target="$((lnum + 1))" '
    BEGIN { FS = "\t" }
    NR == target {
        def_esc($1,  "F_dex_id")
        def_esc($2,  "F_natl")
        def_esc($3,  "F_name")
        def_esc($4,  "F_type1")
        def_esc($5,  "F_type2")
        def_esc($6,  "F_form")
        def_esc($7,  "F_hp")
        def_esc($8,  "F_atk")
        def_esc($9,  "F_def")
        def_esc($10, "F_spa")
        def_esc($11, "F_spd")
        def_esc($12, "F_spe")
        def_esc($13, "F_ab1")
        def_esc($14, "F_ab2")
        def_esc($15, "F_abh")
        def_esc($16, "F_evo_from")
        def_esc($17, "F_evo_meth")
        def_esc($18, "F_evo_into")
        def_esc($19, "F_loc")
        def_esc($20, "F_catch")
        def_esc($21, "F_gender")
        def_esc($22, "F_eg1")
        def_esc($23, "F_eg2")
        def_esc($24, "F_desc")
        exit
    }
    function def_esc(val, varname,    v) {
        v = val
        gsub(/\\/, "\\\\", v)
        gsub(/"/, "\\\"", v)
        gsub(/\047/, "\047\\\\\047\047", v)  # single-quote safe for eval
        printf "%s='"'"'%s'"'"'\n", varname, v
    }
    ' "$data")"

    dex_id="$F_dex_id"
    natl="$F_natl"
    name="$F_name"
    type1="$F_type1"
    type2="$F_type2"
    form="$F_form"
    hp="$F_hp"
    atk="$F_atk"
    def="$F_def"
    spa="$F_spa"
    spd="$F_spd"
    spe="$F_spe"
    ab1="$F_ab1"
    ab2="$F_ab2"
    abh="$F_abh"
    evo_from="$F_evo_from"
    evo_meth="$F_evo_meth"
    evo_into="$F_evo_into"
    loc="$F_loc"
    catch="$F_catch"
    gender="$F_gender"
    eg1="$F_eg1"
    eg2="$F_eg2"
    desc="$F_desc"

    if [ -z "$dex_id" ]; then
        # Row was empty/missing — produce a minimal error slide
        printf '{\n  "selected": 0,\n  "items": [\n    {"text": "No data for entry %s", "background_color": "#333333", "alignment": "middle"}\n  ]\n}\n' "$lnum" > "$DETAIL_JSON"
        return
    fi

    pad=$(printf "%03d" "$dex_id")
    bg=$(type_color "$type1")

    if [ -z "$type2" ]; then ts="$type1"; else ts="$type1 / $type2"; fi

    # ── Slide 1: Identity ────────────────────────────────────────────────────
    slide1="${pad}  ${name}"
    [ -n "$natl" ] && slide1="${slide1}  (Nat. #${natl})"
    slide1="${slide1}\n\nType:  ${ts}"
    [ -n "$form" ]   && slide1="${slide1}\nForm:  ${form}"
    [ -n "$gender" ] && slide1="${slide1}\nGender:  ${gender}"
    [ -n "$catch" ]  && slide1="${slide1}\nCatch rate:  ${catch}"

    if [ -n "$ab1" ] || [ -n "$ab2" ] || [ -n "$abh" ]; then
        slide1="${slide1}\n\nAbilities"
        [ -n "$ab1" ] && slide1="${slide1}\n  ${ab1}"
        [ -n "$ab2" ] && slide1="${slide1}\n  ${ab2}"
        [ -n "$abh" ] && slide1="${slide1}\n  ${abh} (Hidden)"
    fi

    [ -n "$loc" ] && slide1="${slide1}\n\nLocation\n  ${loc}"

    # ── Slide 2: Base Stats ───────────────────────────────────────────────────
    have_stats=0
    for s in "$hp" "$atk" "$def" "$spa" "$spd" "$spe"; do
        [ -n "$s" ] && have_stats=1 && break
    done

    if [ "$have_stats" = "1" ]; then
        total_bs=0
        for s in "$hp" "$atk" "$def" "$spa" "$spd" "$spe"; do
            [ -n "$s" ] && total_bs=$((total_bs + s))
        done

        hp_b=$(stat_bar  "$hp")
        atk_b=$(stat_bar "$atk")
        def_b=$(stat_bar "$def")
        spa_b=$(stat_bar "$spa")
        spd_b=$(stat_bar "$spd")
        spe_b=$(stat_bar "$spe")

        hp_v=${hp:-—};   atk_v=${atk:-—}; def_v=${def:-—}
        spa_v=${spa:-—}; spd_v=${spd:-—}; spe_v=${spe:-—}

        slide2="Base Stats  (Total: ${total_bs})\n\n"
        slide2="${slide2}HP   ${hp_b}  ${hp_v}\n"
        slide2="${slide2}Atk  ${atk_b}  ${atk_v}\n"
        slide2="${slide2}Def  ${def_b}  ${def_v}\n"
        slide2="${slide2}SpA  ${spa_b}  ${spa_v}\n"
        slide2="${slide2}SpD  ${spd_b}  ${spd_v}\n"
        slide2="${slide2}Spe  ${spe_b}  ${spe_v}"
    fi

    # ── Slide 3: Evolution & Pokédex entry ───────────────────────────────────
    have_evo=0
    [ -n "$evo_from" ] || [ -n "$evo_into" ] && have_evo=1

    slide3=""
    if [ "$have_evo" = "1" ]; then
        slide3="Evolution\n"
        if [ -n "$evo_from" ]; then
            meth=""
            [ -n "$evo_meth" ] && meth=" (${evo_meth})"
            slide3="${slide3}  From:  ${evo_from}${meth}\n"
        fi
        [ -n "$evo_into" ] && slide3="${slide3}  Into:  ${evo_into}\n"
    fi

    if [ -n "$eg1" ] || [ -n "$eg2" ]; then
        egg_str="$eg1"
        [ -n "$eg2" ] && egg_str="${eg1} / ${eg2}"
        slide3="${slide3}\nEgg Groups:  ${egg_str}\n"
    fi

    if [ -n "$desc" ]; then
        [ -n "$slide3" ] && slide3="${slide3}\n"
        slide3="${slide3}Pokédex\n  ${desc}"
    fi

    # ── Assemble JSON using printf %s (NOT %b) to avoid re-expanding escapes ──
    {
        printf '{\n  "selected": 0,\n  "items": [\n'
        printf '    {"text": "%s", "background_color": "%s", "alignment": "middle"}' \
            "$slide1" "$bg"

        if [ "$have_stats" = "1" ]; then
            printf ',\n    {"text": "%s", "background_color": "%s", "alignment": "middle"}' \
                "$slide2" "$bg"
        fi

        if [ -n "$slide3" ]; then
            printf ',\n    {"text": "%s", "background_color": "%s", "alignment": "middle"}' \
                "$slide3" "$bg"
        fi

        printf '\n  ]\n}\n'
    } > "$DETAIL_JSON"
}

# =============================================================================
#  POKEMON BROWSE LOOP
# =============================================================================
browse_game() {
    gd="$1"
    # Launch the custom SDL2 Pokedex application within the pak directory
    # so that relative paths for assets (data/sprites, etc) work correctly.
    (cd "$PAK_DIR" && "./bin/arm64/pokedex" "$gd/pokemon.tsv" "$CAUGHT_FILE")
}

# =============================================================================
#  MAIN LOOP
# =============================================================================
main() {
    while true; do
        build_game_list_json

        sel=$(minui-list \
            --file "$GAME_LIST_JSON" \
            --item-key "items" \
            --title "POKEDEX" \
            --title-alignment center \
            --confirm-text "OPEN" \
            --cancel-text "QUIT" \
            --write-value state)

        ec=$?
        [ "$ec" = "2" ] || [ "$ec" = "3" ] && break
        [ "$ec" != "0" ] && break

        sidx=$(printf '%s' "$sel" | grep -o '"selected":[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
        [ -z "$sidx" ] && sidx="0"
        write_setting "selected_game" "$sidx"

        gd=$(get_game_dir_by_index "$sidx")
        [ -z "$gd" ] && continue
        browse_game "$gd"
    done
}

main "$@"
