#!/bin/sh
# =============================================================================
#  Pokedex.pak — Multi-Game Pokédex for NextUI / MinUI (tg5040)
#
#  Data format
#  -----------
#  Each game lives in data/games/<slug>/ and contains:
#    game.conf      — key=value metadata (generated by csv_to_pak.py)
#    pokemon.tsv    — universal tab-separated data (generated by csv_to_pak.py)
#
#  TSV column order (do not change — must match csv_to_pak.py TSV_COLS):
#    1  dex_id         9  spe
#    2  national_id   10  ability1
#    3  name          11  ability2
#    4  type1         12  hidden_ability
#    5  type2         13  evo_from
#    6  form_tag      14  evo_method
#    7  hp            15  evo_into
#    8  atk           16  location
#    9  def           17  catch_rate
#    8  spa           18  gender_ratio
#    9  spd           19  egg_group1
#                     20  egg_group2
#                     21  description
#
#  To add a new game:
#    1. Fill in tools/pokemon.csv and tools/game_meta.csv (see POKEDEX_CSV_SPEC.md)
#    2. Run: python3 tools/csv_to_pak.py --game my-slug
#    3. Copy output/my-slug/ → data/games/my-slug/
# =============================================================================

PAK_DIR="$(dirname "$0")"
PAK_NAME="$(basename "$PAK_DIR")"
PAK_NAME="${PAK_NAME%.*}"

rm -f "$LOGS_PATH/$PAK_NAME.txt"
exec >> "$LOGS_PATH/$PAK_NAME.txt" 2>&1
echo "$0" "$*"
cd "$PAK_DIR" || exit 1

architecture=arm
if uname -m | grep -q '64'; then
    architecture=arm64
fi

export HOME="$SHARED_USERDATA_PATH/$PAK_NAME"
mkdir -p "$HOME"

export PATH="$PAK_DIR/bin/$PLATFORM:$PAK_DIR/bin/$architecture:$PAK_DIR/bin/shared:$PATH"

GAMES_DIR="$PAK_DIR/data/games"
GAME_LIST_JSON="$HOME/game_list.json"
POKE_LIST_JSON="$HOME/poke_list.json"
DETAIL_JSON="$HOME/detail.json"

# ---------- Persistence -------------------------------------------------------
write_setting() { echo "$2" > "$HOME/$1"; }
read_setting()  {
    [ -f "$HOME/$1" ] && cat "$HOME/$1" && return
    [ -n "$2" ] && echo "$2"
}

# ---------- Read a key from game.conf ----------------------------------------
conf_field() {
    grep "^$2=" "$1/game.conf" 2>/dev/null | cut -d= -f2-
}

# ---------- Universal TSV column accessors ------------------------------------
# These match TSV_COLS in csv_to_pak.py exactly.
# Using cut -f avoids IFS read collapsing consecutive empty tabs.
col_dex_id()        { echo "$1" | cut -f1;  }
col_national_id()   { echo "$1" | cut -f2;  }
col_name()          { echo "$1" | cut -f3;  }
col_type1()         { echo "$1" | cut -f4;  }
col_type2()         { echo "$1" | cut -f5;  }
col_form_tag()      { echo "$1" | cut -f6;  }
col_hp()            { echo "$1" | cut -f7;  }
col_atk()           { echo "$1" | cut -f8;  }
col_def()           { echo "$1" | cut -f9;  }
col_spa()           { echo "$1" | cut -f10; }
col_spd()           { echo "$1" | cut -f11; }
col_spe()           { echo "$1" | cut -f12; }
col_ability1()      { echo "$1" | cut -f13; }
col_ability2()      { echo "$1" | cut -f14; }
col_hidden_ability(){ echo "$1" | cut -f15; }
col_evo_from()      { echo "$1" | cut -f16; }
col_evo_method()    { echo "$1" | cut -f17; }
col_evo_into()      { echo "$1" | cut -f18; }
col_location()      { echo "$1" | cut -f19; }
col_catch_rate()    { echo "$1" | cut -f20; }
col_gender_ratio()  { echo "$1" | cut -f21; }
col_egg_group1()    { echo "$1" | cut -f22; }
col_egg_group2()    { echo "$1" | cut -f23; }
col_description()   { echo "$1" | cut -f24; }

# ---------- Type colour -------------------------------------------------------
type_color() {
    case "$1" in
        Normal)   echo "#A8A878" ;;
        Fire)     echo "#F08030" ;;
        Water)    echo "#6890F0" ;;
        Electric) echo "#F8D030" ;;
        Grass)    echo "#78C850" ;;
        Ice)      echo "#98D8D8" ;;
        Fighting) echo "#C03028" ;;
        Poison)   echo "#A040A0" ;;
        Ground)   echo "#E0C068" ;;
        Flying)   echo "#A890F0" ;;
        Psychic)  echo "#F85888" ;;
        Bug)      echo "#A8B820" ;;
        Rock)     echo "#B8A038" ;;
        Ghost)    echo "#705898" ;;
        Dragon)   echo "#7038F8" ;;
        Dark)     echo "#705848" ;;
        Steel)    echo "#B8B8D0" ;;
        Fairy)    echo "#EE99AC" ;;
        *)        echo "#68A090" ;;
    esac
}

# ---------- Stat bar (ASCII fill, max width 20 chars, scale 0-255) -----------
stat_bar() {
    val="$1"
    [ -z "$val" ] && echo "—" && return
    # Scale: 255 → 20 chars
    filled=$(( (val * 20) / 255 ))
    [ "$filled" -gt 20 ] && filled=20
    empty=$((20 - filled))
    bar=""
    i=0
    while [ "$i" -lt "$filled" ]; do bar="${bar}█"; i=$((i+1)); done
    while [ "$i" -lt 20 ];        do bar="${bar}░"; i=$((i+1)); done
    echo "$bar"
}

# =============================================================================
#  GAME SELECT SCREEN
# =============================================================================
build_game_list_json() {
    last=$(read_setting "selected_game" "0")
    printf '{\n  "selected": %s,\n  "items": [\n' "$last" > "$GAME_LIST_JSON"
    first=1
    for gd in "$GAMES_DIR"/*/; do
        [ -f "$gd/game.conf" ] || continue
        [ -f "$gd/pokemon.tsv" ] || continue
        gname=$(conf_field "$gd" "name")
        gyear=$(conf_field "$gd" "year")
        gtype=$(conf_field "$gd" "type")
        gcount=$(conf_field "$gd" "entry_count")
        gdex=$(conf_field "$gd" "dex_label")
        gcolor=$(conf_field "$gd" "color")
        if [ "$gtype" = "fan" ]; then badge="[FAN]"; else badge="[OG] "; fi
        [ "$first" = "1" ] && first=0 || printf ',\n' >> "$GAME_LIST_JSON"
        printf '    {"name": "%s  %s  —  %s  |  %s entries  (%s)", "features": {"background_color": "%s"}}' \
            "$badge" "$gname" "$gdex" "$gcount" "$gyear" "$gcolor" >> "$GAME_LIST_JSON"
    done
    printf '\n  ]\n}\n' >> "$GAME_LIST_JSON"
}

get_game_dir_by_index() {
    target="$1"; idx=0
    for gd in "$GAMES_DIR"/*/; do
        [ -f "$gd/game.conf" ] || continue
        [ -f "$gd/pokemon.tsv" ] || continue
        [ "$idx" = "$target" ] && echo "$gd" && return
        idx=$((idx + 1))
    done
}

# =============================================================================
#  POKEMON LIST
# =============================================================================
build_poke_list_json() {
    gd="$1"
    data="$gd/pokemon.tsv"
    slug="${gd%/}"; slug="${slug##*/}"
    last=$(read_setting "poke_$slug" "0")

    printf '{\n  "selected": %s,\n  "items": [\n' "$last" > "$POKE_LIST_JSON"
    first=1

    total=$(tail -n +2 "$data" | wc -l | tr -d ' ')
    lnum=0
    while [ "$lnum" -lt "$total" ]; do
        lnum=$((lnum + 1))
        row=$(tail -n +2 "$data" | sed -n "${lnum}p")
        [ -z "$row" ] && continue

        dex_id=$(col_dex_id   "$row")
        name=$(col_name       "$row")
        type1=$(col_type1     "$row")
        type2=$(col_type2     "$row")
        form=$(col_form_tag   "$row")

        [ -z "$dex_id" ] && continue

        pad=$(printf "%03d" "$dex_id")

        if [ -z "$type2" ]; then ts="$type1"; else ts="${type1}/${type2}"; fi

        if [ -n "$form" ]; then
            lbl="#${pad}  ${name}  [${ts}]  (${form})"
        else
            lbl="#${pad}  ${name}  [${ts}]"
        fi

        col=$(type_color "$type1")
        [ "$first" = "1" ] && first=0 || printf ',\n' >> "$POKE_LIST_JSON"
        printf '    {"name": "%s", "features": {"background_color": "%s"}}' "$lbl" "$col" \
            >> "$POKE_LIST_JSON"
    done
    printf '\n  ]\n}\n' >> "$POKE_LIST_JSON"
}

# =============================================================================
#  DETAIL VIEW  — three slides, each shown only when data exists
# =============================================================================
build_detail_json() {
    gd="$1"; lnum="$2"
    data="$gd/pokemon.tsv"
    row=$(tail -n +2 "$data" | sed -n "${lnum}p")

    dex_id=$(col_dex_id        "$row")
    natl=$(col_national_id     "$row")
    name=$(col_name            "$row")
    type1=$(col_type1          "$row")
    type2=$(col_type2          "$row")
    form=$(col_form_tag        "$row")
    hp=$(col_hp                "$row")
    atk=$(col_atk              "$row")
    def=$(col_def              "$row")
    spa=$(col_spa              "$row")
    spd=$(col_spd              "$row")
    spe=$(col_spe              "$row")
    ab1=$(col_ability1         "$row")
    ab2=$(col_ability2         "$row")
    abh=$(col_hidden_ability   "$row")
    evo_from=$(col_evo_from    "$row")
    evo_meth=$(col_evo_method  "$row")
    evo_into=$(col_evo_into    "$row")
    loc=$(col_location         "$row")
    catch=$(col_catch_rate     "$row")
    gender=$(col_gender_ratio  "$row")
    eg1=$(col_egg_group1       "$row")
    eg2=$(col_egg_group2       "$row")
    desc=$(col_description     "$row")

    pad=$(printf "%03d" "$dex_id")
    bg=$(type_color "$type1")

    if [ -z "$type2" ]; then ts="$type1"; else ts="$type1 / $type2"; fi

    # ── Slide 1: Identity ────────────────────────────────────────────────────
    slide1="${pad}  ${name}"
    [ -n "$natl" ] && slide1="${slide1}  (Nat. #${natl})"
    slide1="${slide1}\n\nType:  ${ts}"
    [ -n "$form" ]   && slide1="${slide1}\nForm:  ${form}"
    [ -n "$gender" ] && slide1="${slide1}\nGender:  ${gender}"
    [ -n "$catch" ]  && slide1="${slide1}\nCatch rate:  ${catch}"

    # Abilities block
    if [ -n "$ab1" ] || [ -n "$ab2" ] || [ -n "$abh" ]; then
        slide1="${slide1}\n\nAbilities"
        [ -n "$ab1" ] && slide1="${slide1}\n  ${ab1}"
        [ -n "$ab2" ] && slide1="${slide1}\n  ${ab2}"
        [ -n "$abh" ] && slide1="${slide1}\n  ${abh} (Hidden)"
    fi

    # Location block
    if [ -n "$loc" ]; then
        slide1="${slide1}\n\nLocation\n  ${loc}"
    fi

    # ── Slide 2: Base Stats (only if at least one stat present) ──────────────
    have_stats=0
    for s in "$hp" "$atk" "$def" "$spa" "$spd" "$spe"; do
        [ -n "$s" ] && have_stats=1 && break
    done

    if [ "$have_stats" = "1" ]; then
        total_bs=0
        for s in "$hp" "$atk" "$def" "$spa" "$spd" "$spe"; do
            [ -n "$s" ] && total_bs=$((total_bs + s))
        done

        hp_b=$(stat_bar  "$hp")
        atk_b=$(stat_bar "$atk")
        def_b=$(stat_bar "$def")
        spa_b=$(stat_bar "$spa")
        spd_b=$(stat_bar "$spd")
        spe_b=$(stat_bar "$spe")

        hp_v=${hp:-—};  atk_v=${atk:-—}; def_v=${def:-—}
        spa_v=${spa:-—}; spd_v=${spd:-—}; spe_v=${spe:-—}

        slide2="Base Stats  (Total: ${total_bs})\n\n"
        slide2="${slide2}HP   ${hp_b}  ${hp_v}\n"
        slide2="${slide2}Atk  ${atk_b}  ${atk_v}\n"
        slide2="${slide2}Def  ${def_b}  ${def_v}\n"
        slide2="${slide2}SpA  ${spa_b}  ${spa_v}\n"
        slide2="${slide2}SpD  ${spd_b}  ${spd_v}\n"
        slide2="${slide2}Spe  ${spe_b}  ${spe_v}"
    fi

    # ── Slide 3: Evolution & Pokédex entry ───────────────────────────────────
    have_evo=0
    [ -n "$evo_from" ] || [ -n "$evo_into" ] && have_evo=1

    slide3=""
    if [ "$have_evo" = "1" ]; then
        slide3="Evolution\n"
        if [ -n "$evo_from" ]; then
            meth=""
            [ -n "$evo_meth" ] && meth=" (${evo_meth})"
            slide3="${slide3}  From:  ${evo_from}${meth}\n"
        fi
        if [ -n "$evo_into" ]; then
            slide3="${slide3}  Into:  ${evo_into}\n"
        fi
    fi

    if [ -n "$eg1" ] || [ -n "$eg2" ]; then
        egg_str="$eg1"
        [ -n "$eg2" ] && egg_str="${eg1} / ${eg2}"
        slide3="${slide3}\nEgg Groups:  ${egg_str}\n"
    fi

    if [ -n "$desc" ]; then
        [ -n "$slide3" ] && slide3="${slide3}\n"
        slide3="${slide3}Pokédex\n  ${desc}"
    fi

    # ── Assemble JSON ─────────────────────────────────────────────────────────
    # Build the items array — only include slides that have content
    items_json=""

    items_json="${items_json}    {\"text\": \"${slide1}\", \"background_color\": \"${bg}\", \"alignment\": \"middle\"}"

    if [ "$have_stats" = "1" ]; then
        items_json="${items_json},\n    {\"text\": \"${slide2}\", \"background_color\": \"${bg}\", \"alignment\": \"middle\"}"
    fi

    if [ -n "$slide3" ]; then
        items_json="${items_json},\n    {\"text\": \"${slide3}\", \"background_color\": \"${bg}\", \"alignment\": \"middle\"}"
    fi

    printf '{\n  "selected": 0,\n  "items": [\n%b\n  ]\n}\n' "$items_json" > "$DETAIL_JSON"
}

# =============================================================================
#  POKEMON BROWSE LOOP
# =============================================================================
browse_game() {
    gd="$1"
    gname=$(conf_field "$gd" "name")
    slug="${gd%/}"; slug="${slug##*/}"

    while true; do
        build_poke_list_json "$gd"

        sel=$(minui-list \
            --file "$POKE_LIST_JSON" \
            --item-key "items" \
            --title "$gname" \
            --title-alignment center \
            --confirm-text "VIEW" \
            --cancel-text "BACK" \
            --write-value state)

        ec=$?
        [ "$ec" = "2" ] || [ "$ec" = "3" ] && return
        [ "$ec" != "0" ] && return

        sidx=$(printf '%s' "$sel" | grep -o '"selected":[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
        [ -z "$sidx" ] && sidx="0"
        write_setting "poke_$slug" "$sidx"

        build_detail_json "$gd" "$((sidx + 1))"

        minui-presenter \
            --file "$DETAIL_JSON" \
            --show-b-button \
            --b-text "BACK"
    done
}

# =============================================================================
#  MAIN LOOP
# =============================================================================
main() {
    while true; do
        build_game_list_json

        sel=$(minui-list \
            --file "$GAME_LIST_JSON" \
            --item-key "items" \
            --title "POKEDEX" \
            --title-alignment center \
            --confirm-text "OPEN" \
            --cancel-text "QUIT" \
            --write-value state)

        ec=$?
        [ "$ec" = "2" ] || [ "$ec" = "3" ] && break
        [ "$ec" != "0" ] && break

        sidx=$(printf '%s' "$sel" | grep -o '"selected":[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
        [ -z "$sidx" ] && sidx="0"
        write_setting "selected_game" "$sidx"

        gd=$(get_game_dir_by_index "$sidx")
        [ -z "$gd" ] && continue
        browse_game "$gd"
    done
}

main "$@"
